# Generated by Django 2.1.5 on 2019-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_name', models.CharField(max_length=4)),
                ('upper', models.IntegerField()),
                ('lower', models.IntegerField()),
                ('middle', models.IntegerField()),
                ('side', models.IntegerField()),
                ('total', models.IntegerField(default=8)),
            ],
        ),
    ]
