# Generated by Django 2.1.5 on 2019-01-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=15)),
                ('coach_name', models.CharField(default=None, max_length=4)),
                ('upper', models.IntegerField(default=None)),
                ('lower', models.IntegerField(default=None)),
                ('middle', models.IntegerField(default=None)),
                ('side', models.IntegerField(default=None)),
            ],
        ),
    ]
